// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    $('#str').keyup(function() {
      return $('#result').val(convert_gksdud($('#str').val()));
    });
    $('.menu-home').click(function() {
      $('#container-home').css('display', 'block');
      $('#container-about').css('display', 'none');
      $('.menu-home').addClass('active');
      return $('.menu-about').removeClass('active');
    });
    return $('.menu-about').click(function() {
      $('#container-about').css('display', 'block');
      $('#container-home').css('display', 'none');
      $('.menu-about').addClass('active');
      return $('.menu-home').removeClass('active');
    });
  });

}).call(this);
